export const ROUTE_API = {
  ticketList: "/tickets",
  ratingList: "/custom_field/rating",
  levelList: "/custom_field/level",
  statusList: "/custom_field/ticket-status",
  technicalsList: "/custom_field/technical",
  departmentList: "/custom_field/department",
  login: "/auth/login",
  updatesurvey: "/tickets/update-survey/",
  getsurvey: "/tickets/",
  exportData: "/tickets/export-to-excel",
  onlineReport: "/tickets/reports/online-reports",
  onlineExport: "/tickets/reports/online-reports/export-to-excel",
  ihReport: "/tickets/reports/ih-reports",
  ihExport: "/tickets/reports/online-reports/export-to-excel",
};
